// <auto-generated />
using System;
using AcademicProjectManager.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicProjectManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AcademicProjectManager.Data.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.johnson@acme.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Role = "Project Manager"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.smith@acme.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            Role = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carol.white@acme.com",
                            FirstName = "Carol",
                            LastName = "White",
                            Role = "QA Engineer"
                        },
                        new
                        {
                            Id = 4,
                            Email = "david.brown@acme.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Role = "Developer"
                        },
                        new
                        {
                            Id = 5,
                            Email = "emma.davis@acme.com",
                            FirstName = "Emma",
                            LastName = "Davis",
                            Role = "Designer"
                        });
                });

            modelBuilder.Entity("AcademicProjectManager.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete redesign of the mobile application for improved UX and performance.",
                            IsCompleted = false,
                            StartDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Mobile App Redesign"
                        },
                        new
                        {
                            Id = 2,
                            Deadline = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Migrate legacy backend APIs to microservices architecture.",
                            IsCompleted = false,
                            StartDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Backend API Migration"
                        },
                        new
                        {
                            Id = 3,
                            Deadline = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Performance tuning and query optimization for production database.",
                            IsCompleted = false,
                            StartDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Database Optimization"
                        });
                });

            modelBuilder.Entity("AcademicProjectManager.Data.Entities.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMemberId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedMemberId = 5,
                            AssignedOn = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletedOn = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create high-fidelity mockups for the new onboarding experience.",
                            IsOverdue = false,
                            ProjectId = 1,
                            Status = 3,
                            Title = "Design mockups for onboarding flow"
                        },
                        new
                        {
                            Id = 2,
                            AssignedMemberId = 2,
                            AssignedOn = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build React components for redesigned screens.",
                            IsOverdue = false,
                            ProjectId = 1,
                            Status = 2,
                            Title = "Implement UI components"
                        },
                        new
                        {
                            Id = 3,
                            AssignedMemberId = 3,
                            AssignedOn = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test integration between UI and backend services.",
                            IsOverdue = false,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Integration testing"
                        },
                        new
                        {
                            Id = 4,
                            AssignedMemberId = 1,
                            AssignedOn = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Coordinate with stakeholders for UAT feedback.",
                            IsOverdue = false,
                            ProjectId = 1,
                            Status = 1,
                            Title = "User acceptance testing"
                        },
                        new
                        {
                            Id = 5,
                            AssignedMemberId = 4,
                            AssignedOn = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletedOn = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Review and finalize microservices architecture.",
                            IsOverdue = false,
                            ProjectId = 2,
                            Status = 3,
                            Title = "Architecture design review"
                        },
                        new
                        {
                            Id = 6,
                            AssignedMemberId = 2,
                            AssignedOn = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new authentication microservice.",
                            IsOverdue = false,
                            ProjectId = 2,
                            Status = 2,
                            Title = "Implement authentication service"
                        },
                        new
                        {
                            Id = 7,
                            AssignedMemberId = 4,
                            AssignedOn = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new payment processing microservice.",
                            IsOverdue = false,
                            ProjectId = 2,
                            Status = 2,
                            Title = "Implement payment service"
                        },
                        new
                        {
                            Id = 8,
                            AssignedMemberId = 2,
                            AssignedOn = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Write and test migration scripts for existing data.",
                            IsOverdue = false,
                            ProjectId = 2,
                            Status = 1,
                            Title = "Data migration scripts"
                        },
                        new
                        {
                            Id = 9,
                            AssignedMemberId = 4,
                            AssignedOn = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conduct load tests and optimize for production scale.",
                            IsOverdue = false,
                            ProjectId = 2,
                            Status = 1,
                            Title = "Load testing and optimization"
                        },
                        new
                        {
                            Id = 10,
                            AssignedMemberId = 4,
                            AssignedOn = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletedOn = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Analyze query patterns and create optimized indexes.",
                            IsOverdue = false,
                            ProjectId = 3,
                            Status = 3,
                            Title = "Index analysis and creation"
                        },
                        new
                        {
                            Id = 11,
                            AssignedMemberId = 4,
                            AssignedOn = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rewrite slow queries for better performance.",
                            IsOverdue = false,
                            ProjectId = 3,
                            Status = 2,
                            Title = "Query optimization"
                        },
                        new
                        {
                            Id = 12,
                            AssignedMemberId = 3,
                            AssignedOn = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Benchmark before/after performance metrics.",
                            IsOverdue = false,
                            ProjectId = 3,
                            Status = 1,
                            Title = "Performance benchmarking"
                        });
                });

            modelBuilder.Entity("AcademicProjectManager.Data.Entities.ProjectTask", b =>
                {
                    b.HasOne("AcademicProjectManager.Data.Entities.Member", "AssignedMember")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademicProjectManager.Data.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedMember");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AcademicProjectManager.Data.Entities.Member", b =>
                {
                    b.Navigation("AssignedTasks");
                });

            modelBuilder.Entity("AcademicProjectManager.Data.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
